# From HEROKU DOCUMENTATION
# https://devcenter.heroku.com/articles/ruby-support#build-behavior
# ==============================================================================
# When an application is deployed, the build phase configures the underlying Rack 
# or Rails application to use the provisioned database if a config directory 
# exists, and a RAILS_ENV or RACK_ENV environment variable is present. Under these
# conditions, a database.yml file will be created . If a database.yml file 
# already exists, it will be replaced. The database.yml file is created as Ruby 
# code that dynamically creates its output by parsing the DATABASE_URL environment 
# variable.

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

#Leave this alone
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test